version: "2.4"

services:
  animals_classifier:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    build: ./classifier/build
    volumes:
      - ./classifier/app:/app/
      - ./classifier/app/weights:/app/weights
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    env_file:
      - .env
    networks:
      - ml_experiments_network

networks:
  ml_experiments_network:
    name: experiments_network
    external: true
